# Generated by Django 5.0.1 on 2024-02-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chill', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
